services:
  php8.2:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PHP_VERSION: 8.2
    volumes:
      - ./:/app
      - /app/vendor

  php8.3:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PHP_VERSION: 8.3
    volumes:
      - ./:/app
      - /app/vendor

  php8.4:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PHP_VERSION: 8.4
    volumes:
      - ./:/app
      - /app/vendor

  php8.5:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PHP_VERSION: 8.5
    volumes:
      - ./:/app
      - /app/vendor
